spring.application.name=headless-cms

# Swagger Path
springdoc.swagger-ui.path=/docs

# ======================================================================================================================
#                                            DATABASE CONFIGURATION
# ======================================================================================================================

# ======================================================================================================================
#                                            LOCAL DOCKER POSTGRESQL
# ======================================================================================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/cmsdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# ======================================================================================================================
#                                                   DEPLOYMENT
# ======================================================================================================================

# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}
# spring.datasource.hikari.data-source-properties.sslmode=require

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# JWT
# ===============================
jwt.secret=Y0lNU19TRUNSRVRfS0VZX0ZPUl9IRUFETEVTU19DTVM=
jwt.expiration=3600000