spring.application.name=headless-cms


# Swagger Path Setting
springdoc.swagger-ui.path=/docs 

# Database Configuration
spring.datasource.database = CMSDB
spring.datasource.url=jdbc:mysql://localhost:3306/${spring.datasource.database}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zaid
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=Y0lNU19TRUNSRVRfS0VZX0ZPUl9IRUFETEVTU19DTVM=
jwt.expiration=3600000