spring.application.name=headless-cms


# Swagger Path Setting
springdoc.swagger-ui.path=/docs


# ===============================
# Database (PostgreSQL - Render)
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# JWT
# ===============================

jwt.secret=Y0lNU19TRUNSRVRfS0VZX0ZPUl9IRUFETEVTU19DTVM=
jwt.expiration=3600000